overrides:
  mutation_mode: all
transport:
  type: streamable_http
  address: 127.0.0.1
  port: 5000
operations:
  source: collection
  id: default #<- is this needed or is it defaulted?
  
# If you are running the Apollo Router locally, comment out this line
endpoint: https://router-template-production.up.railway.app/
